# Generated by Django 4.2.1 on 2024-01-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_paste_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='language',
        ),
    ]
